CREATE TABLE download_token (
	dto_id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
	dto_fil_id BIGINT(20) UNSIGNED NOT NULL,
	dto_usr_id BIGINT(20) UNSIGNED NULL DEFAULT NULL,
	dto_token CHAR(64) NOT NULL,
	dto_user_ip VARBINARY(16) NOT NULL,
	dto_create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	dto_expire_date DATETIME NOT NULL,
	PRIMARY KEY (dto_id)
);
