CREATE TABLE user_logon (
	ulo_id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
	ulo_usr_id BIGINT(20) UNSIGNED NOT NULL,
	ulo_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	ulo_ip VARBINARY(16) NOT NULL,
	ulo_error SMALLINT(6) NOT NULL DEFAULT -1,
	ulo_error_message VARCHAR(255) NULL DEFAULT NULL,
	PRIMARY KEY (ulo_id)
);
